In [45]:
import numpy as np 
import pandas as pd 

path = 'C:/Users/priye/OneDrive/Desktop/DataPer/MScDataScience/InternshipVideoAnalytics/Titanic data/'

df_train = pd.read_csv(path + "train.csv")
df_test = pd.read_csv(path + "test.csv")


In [15]:
df_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [16]:
#for training dataset

df_train = df_train.drop(columns= ['PassengerId','Name','Age','Ticket','Fare','Cabin','Embarked'])
df_train['Sex'].replace({'female':0,'male':1},inplace=True)
df_train

train_data = df_train.values

X = train_data[:,1:5]
Y = train_data[:,0]

In [17]:
train_data

array([[0, 3, 1, 1, 0],
       [1, 1, 0, 1, 0],
       [1, 3, 0, 0, 0],
       ...,
       [0, 3, 0, 1, 2],
       [1, 1, 1, 0, 0],
       [0, 3, 1, 0, 0]], dtype=int64)

In [18]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [19]:
X_scale

array([[1.        , 1.        , 0.125     , 0.        ],
       [0.        , 0.        , 0.125     , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       ...,
       [1.        , 0.        , 0.125     , 0.33333333],
       [0.        , 1.        , 0.        , 0.        ],
       [1.        , 1.        , 0.        , 0.        ]])

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val = train_test_split(X_scale, Y, test_size=0.3)


In [22]:
print(X_train.shape, X_val.shape, Y_train.shape, Y_val.shape)


(623, 4) (268, 4) (623,) (268,)


In [54]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([Dense(32, activation='relu', input_shape=(4,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid'),])
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, Y_train,
          batch_size=32, epochs=100,
          validation_data=(X_val, Y_val))


Epoch 1/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6975 - accuracy: 0.4109 - val_loss: 0.6774 - val_accuracy: 0.6194
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6696 - accuracy: 0.6035 - val_loss: 0.6509 - val_accuracy: 0.6306
Epoch 3/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6502 - accuracy: 0.6100 - val_loss: 0.6333 - val_accuracy: 0.6306
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6378 - accuracy: 0.6100 - val_loss: 0.6211 - val_accuracy: 0.6306
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6286 - accuracy: 0.6100 - val_loss: 0.6122 - val_accuracy: 0.6306
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6215 - accuracy: 0.6100 - val_loss: 0.6047 - val_accuracy: 0.6306
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6155 - accuracy: 0.6100 - val_loss: 0.5978 - val_accuracy: 0.6306
Epoch 8/100
2

In [41]:
model.evaluate(X_val, Y_val)[1]


9/9 [==============================] - 0s 667us/step - loss: 0.4564 - accuracy: 0.8172


0.8171641826629639

In [46]:
df_test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [47]:
df_test = df_test.drop(columns= ['PassengerId','Name','Age','Ticket','Fare','Cabin','Embarked'])
df_test['Sex'].replace({'female':0,'male':1},inplace=True)

In [48]:
X_test = df_test.values

In [49]:
X_test

array([[3, 1, 0, 0],
       [3, 0, 1, 0],
       [2, 1, 0, 0],
       ...,
       [3, 1, 0, 0],
       [3, 1, 0, 0],
       [3, 1, 1, 1]], dtype=int64)

In [50]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
Xtest_scale = min_max_scaler.fit_transform(X_test)

In [51]:
Xtest_scale

array([[1.        , 1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.125     , 0.        ],
       [0.5       , 1.        , 0.        , 0.        ],
       ...,
       [1.        , 1.        , 0.        , 0.        ],
       [1.        , 1.        , 0.        , 0.        ],
       [1.        , 1.        , 0.125     , 0.11111111]])

In [55]:
predictions = model.predict(Xtest_scale)


In [56]:
predictions

array([[0.11880881],
       [0.5812645 ],
       [0.21297538],
       [0.11880881],
       [0.5929885 ],
       [0.11880881],
       [0.5883229 ],
       [0.21617734],
       [0.5883229 ],
       [0.10820726],
       [0.11880881],
       [0.39618954],
       [0.80842155],
       [0.20741099],
       [0.80842155],
       [0.7350859 ],
       [0.21297538],
       [0.11880881],
       [0.5812645 ],
       [0.5883229 ],
       [0.38537896],
       [0.12566599],
       [0.80564487],
       [0.40516073],
       [0.78949916],
       [0.11339575],
       [0.8018192 ],
       [0.11880881],
       [0.39618954],
       [0.10820726],
       [0.20741099],
       [0.20236614],
       [0.59967834],
       [0.59967834],
       [0.38537896],
       [0.11880881],
       [0.5883229 ],
       [0.5883229 ],
       [0.11880881],
       [0.11880881],
       [0.12566599],
       [0.39618954],
       [0.11880881],
       [0.7510842 ],
       [0.80842155],
       [0.11880881],
       [0.39618954],
       [0.118